kind: pipeline
type: docker
name: build-and-push-docker-image

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.20
  commands:
  - go build -o myapp

- name: docker-build-and-push
  image: docker
  commands:
  - docker build -t myregistry.com/myapp:pr-${DRONE_PULL_REQUEST} .
  - docker push myregistry.com/myapp:pr-${DRONE_PULL_REQUEST}
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - pull_request
